name: Build Call Away App

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:

      - name: test run
        run: echo building android apk for call-away

  build-ios:
    runs-on: macos-latest

    steps:

      - name: test run
        run: echo building android apk for call-away
