name: Build Call Away App

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

  build-ios:
    runs-on: macos-latest

    steps:

      - name: test run
        run: echo building android apk for call-away
