name: Build Call Away App

on:
  workflow_dispatch:

jobs:
  build-android:
    environment: TEST
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"

      - name: Install dependencies
        run: flutter pub get

      - name: set environment secrets
        run: |
          printf "const sKey=\"%s\";\nconst cKey=\"%s\";\n" ${{ secrets.SKEY }} ${{ secrets.CKEY }} > lib/my_env.dart

      - name: Build apk release
        run: flutter build apk --release

      - name: Uplioad build artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: call-away.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:

      - name: test run
        run: echo building android apk for call-away
